### ISSUE TITLE
ERR_INVALID_ARG_TYPE issue with custom S3 endpoint

### ISSUE THREAD

**Issue by ouun** [humanmade/tachyon#127]
I am experimenting with Tachyon and a S3 that is not based on AWS. Everything works as expected and I can get the manipulated images as it should be. The only issue I have is the following:

```
server > TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type object
server >     at write_ (_http_outgoing.js:595:11)
server >     at ServerResponse.write (_http_outgoing.js:567:10)
server >     at callback (/home/user/node-tachyon/server.js:61:15)
server >     at /home/user/node-tachyon/server.js:78:11
server >     at Response.<anonymous> (/home/user/node-tachyon/index.js:72:11)
server >     at Request.<anonymous> (/home/user/node-tachyon/node_modules/aws-sdk/lib/request.js:364:18)
server >     at Request.callListeners (/home/user/node-tachyon/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
server >     at Request.emit (/home/user/node-tachyon/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
server >     at Request.emit (/home/user/node-tachyon/node_modules/aws-sdk/lib/request.js:683:14)
server >     at Request.transition (/home/user/node-tachyon/node_modules/aws-sdk/lib/request.js:22:10)
```

I tried to find the issue, but do not understand when the error is coming up. Any idea or hint would be very appriciated. 

Thanks

**Comment by ouun** [comment]
Closing this as I found the issue: Each request to a Tachyon URL also requested /favicon.ico. So Tachyon always answered with the actual image response and a 502-error for the favicon.
