### ISSUE TITLE
Non-existent image returns 200 with empty body

### ISSUE THREAD

**Issue by jerico** [humanmade/tachyon#176]
In 2.x code, when `AccessDenied` error returned from S3, Tachyon responded with a status code of 404. https://github.com/humanmade/tachyon/blob/v2.6.3/lambda-handler.js#L21-L30

Reviewing the code in version 3 (specifically the `lambda-handler.ts` file), it seems that the behavior of responding with a 404 status code for an ﻿`AccessDenied` error from S3 is not implemented resulting in getting a 200 response with an empty body for non-existent files.
  
Lambda log
```
{
    "errorType": "AccessDenied",
    "errorMessage": "Access Denied",
    "name": "AccessDenied",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 403,
        "requestId": "XXXXX",
        "extendedRequestId": "XXXXX",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "Code": "AccessDenied",
    "RequestId": "XXXXX",
    "HostId": "XXXXX",
    "message": "Access Denied",
    "stack": [
        "AccessDenied: Access Denied",
        "    at throwDefaultError (/var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:8:22)",
        "    at /var/task/node_modules/@smithy/smithy-client/dist-cjs/default-error-handler.js:18:39",
        "    at de_GetObjectCommandError (/var/task/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4330:20)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at async /var/task/node_modules/@smithy/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
        "    at async /var/task/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20",
        "    at async /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
        "    at async /var/task/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20",
        "    at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
        "    at async Runtime.streamify_handler [as handler] (file:///var/task/dist/lambda-handler.js:26:23)"
    ]
}
```

**Comment by jerico** [comment]
I tried working on this but could not figure out how to change the status code from a streamed response.

Here's a WIP that returns "File not found" in body if there's an error. But the status code is still `200`: https://github.com/humanmade/tachyon/pull/177
