### ISSUE TITLE
403 (Forbidden) https://dl.bintray.com/lovell/sharp/libvips-8.4.2-darwin-x64.tar.gz

### ISSUE THREAD

**Issue by stevegibbings** [humanmade/tachyon#46]
Getting a failure on install on download of https://dl.bintray.com/lovell/sharp/libvips-8.4.2-darwin-x64.tar.gz with a 403 (Forbidden)

We are using commit 1b776d01aff6a58347468d24c8a90d6f44e5d4bc but does the same on master too.

```> sharp@0.17.3 install /Users/steve.gibbings/WebstormProjects/tachyon/node_modules/sharp
> node-gyp rebuild

ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.4.2-darwin-x64.tar.gz failed: Response code 403 (Forbidden)
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/steve.gibbings/WebstormProjects/tachyon/node_modules/sharp
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-tachyon@2.1.1 /Users/steve.gibbings/WebstormProjects/tachyon
├─┬ animated-gif-detector@1.2.0
│ └── inherits@2.0.3
├─┬ aws-sdk@2.124.0
│ ├─┬ buffer@4.9.1
│ │ ├── base64-js@1.2.1
│ │ ├── ieee754@1.1.8
│ │ └── isarray@1.0.0
│ ├── crypto-browserify@1.0.9
│ ├── events@1.1.1
│ ├── jmespath@0.15.0
│ ├── querystring@0.2.0
│ ├── sax@1.2.1
│ ├─┬ url@0.10.3
│ │ └── punycode@1.3.2
│ ├── uuid@3.0.1
│ ├── xml2js@0.4.17
│ └─┬ xmlbuilder@4.2.1
│   └── lodash@4.17.4
├─┬ cli-table@0.3.1
│ └── colors@1.0.3
└── filesize@3.5.10

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steve.gibbings/WebstormProjects/tachyon/npm-debug.lo
```

**Comment by stevegibbings** [comment]
Sorry known issue on sharp. https://github.com/lovell/sharp/issues/964 So this just FYI
